name: Headless Video Looper

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Video URL to loop'
        required: true
        type: string
      loops:
        description: 'Number of loops'
        required: true
        type: string

jobs:
  video-loop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Run video looper
        run: |
          python multi.py "${{ github.event.inputs.video_url }}" "${{ github.event.inputs.loops }}"
